version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=chatapp
      - MYSQL_USER=chatuser
      - MYSQL_PASSWORD=chatpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - spring_datasource_url=jdbc:mysql://db:3306/chatapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - spring_datasource_username=chatuser
      - spring_datasource_password=chatpass
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
