spring:
  datasource:
    url: jdbc:mysql://mysql:3306/chatapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chatuser
    password: chatpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
